### ISSUE TITLE
Unexpected end of file error during deployment

### ISSUE THREAD

**Issue by trych** [johannschopplich/kirby-blurry-placeholder#1]
Hi there!

Thanks a lot for this plugin. During my local testing (using Lavarel Valet) it worked really nicely, but now when I try to deploy my site (on uberspace.de), I get an `unexpected end of file` syntax error, referring to the `/classes/KirbyExtended/BlurryPlaceholder.php` file. See screenshot.

![20200925-232640_Screenshot_GoogleChrome](https://user-images.githubusercontent.com/9803905/94317707-2256c080-ff87-11ea-8ae3-4c58b07dd9f2.png)

I am not really a php expert, upon first glance I don't see what's wrong (and also, it works locally, so I'm a bit confused).
Is there any quick fix for this issue?

Thanks a lot!

**Comment by johannschopplich** [comment]
From the information given in the screenshot I can't track down an error either. Have you made sure you're running at least PHP 7.3? You may execute: `uberspace tools version show php`

It seems like a generic issue, which could be thrown from an error outside the plugin. Could you please delete the plugin from your server and run the website again?

**Comment by trych** [comment]
🤦‍♂️
Yes, my bad. I thought this was a really new uberspace and assumed it had the most recent PHP version. Turns out, it was an older uberspace with a brand new domain only. Updating it to above php 7.2 fixes the issue. Thanks a lot!

**Comment by johannschopplich** [comment]
No problem! Glad you've figured it out. 🙂
