### ISSUE TITLE
[Question] Best Slider to use with this plugin (and thus loodeer)

### ISSUE THREAD

**Issue by bnomei** [johannschopplich/kirby-blurry-placeholder#10]
i usually use https://flickity.metafizzy.co/ as a slider but its a bit of a hassle to get the cell height right with lazy loaded images even with aspect ratio tricks etc.

what slider whould you recommend? for plain html and in vue?

**Comment by bnomei** [comment]
Ah you said this on discord:
> The aspect-ratio can be omitted (although fancy; until browser support improves) if plain old width and height are provided. Which the plugin does. Thus, we will prevent content reflow.

and that pretty much should solve my issue. i will give it a try asap.

**Comment by johannschopplich** [comment]
Yeah, I know exactly what you mean. Took me some time to get the cell height fluid. That's how I have implemented Flickity.

- Cell image: https://github.com/johannschopplich/johannschopplich.com/blob/main/site/snippets/photography/carousel.php#L10
- CSS: https://github.com/johannschopplich/johannschopplich.com/blob/main/src/scss/pages/home.scss#L19
