### ISSUE TITLE
Division by zero Error (image inside Structure Field)

### ISSUE THREAD

**Issue by manuel-fleig** [johannschopplich/kirby-blurry-placeholder#16]
Hey, I´m getting the following error when using the plugin for images inside a structure field:

```
Whoops \ Exception \ ErrorException (E_WARNING):
Division by zero
```

it's in this line of site/plugins/kirby-blurry-placeholder/classes/KirbyExtended/BlurryPlaceholder.php:

`$height = sqrt($pixelTarget / ($ratio ?? $file->ratio()));`

What might be wrong here?

**Comment by johannschopplich** [comment]
Are you sure your `image` is actually an image? Doesn't seem that way. The [`ratio()`](https://getkirby.com/docs/reference/objects/image/image/ratio) method will work on images solely.

Could you provide a minimal reproducible example?

**Comment by manuel-fleig** [comment]
Yep, sure:

```
<?php $items = $page->projects()->toStructure()->shuffle()?>
    <?php foreach ($items as $item): ?>
    <div>
        <img src="<?= $item->project()->toFile()->placeholderUri() ?>"
            data-src="<?= $item->project()->toFile()->url() ?>" data-lazyload
            alt="<?= $item->project()->toFile()->alt() ?>" />
    </div>
    <?php endforeach ?>
```

it works perfectly on all other pages, but here it crashes.

**Comment by johannschopplich** [comment]
Could you implement a safeguard?

```php
<?php foreach ($items as $item): ?>
  <?php if (!$item->project()->toFile()) continue ?>
```

Actually, I postulate that it's not the plugin, but an error in the data structure.

**Comment by manuel-fleig** [comment]
Found the mistake, haha. You were right in the first place. There was a PDF between the images i didn't notice.

Thanks for the quick Support @johannschopplich , i really love your plugin :)

**Comment by johannschopplich** [comment]
Thanks, glad to hear you're enjoying the plugin and also found the bug! 🙂
