### ISSUE TITLE
Get placeholder data via API/KQL

### ISSUE THREAD

**Issue by hansipete** [johannschopplich/kirby-blurry-placeholder#26]
Is there any chance to use Kirby Query Language to get placeholder data?

I tried the following — It was a desperate shot in the dark and with no success :-)

```
...
photo: {
  query: "page.photos.toFiles.first",
  select: {
    url: true,
    placeholderUri: true,
    focus: true
  }
}
```

Maybe that's more of a KQL-Question on how to call fieldMethods in a query...

**Comment by johannschopplich** [comment]
I have added support for KQL. Glad you asked!

Usage should work as shown below. The `placeholder` and `placeholderUri` file methods are now accessible via KQL:

```ts
photo: {
  query: "page.photos.toFiles.first",
  select: {
    url: true,
    hash: "file.placeholderUri",
    focus: true
  }
}
```
