### ISSUE TITLE
Update auto sizes on resize

### ISSUE THREAD

**Issue by arnoson** [johannschopplich/kirby-blurry-placeholder#3]
Would it be possible to update the automatically generated sizes when the window is resized?

**Comment by johannschopplich** [comment]
Of course, thanks for asking: https://github.com/johannschopplich/kirby-blurry-placeholder/releases/tag/v1.2.0

Please test it. Feedback appreciated.

**Comment by arnoson** [comment]
Wow that was quick! Will test it with an new project and report how it works
Thank you

**Comment by trych** [comment]
Quick question: Is this supposed to recalculate and update the value of the `sizes` attribute? Because it does not change when I am resizing the window.

Am I missing something?
