### ISSUE TITLE
Artifacts when using transparent images

### ISSUE THREAD

**Issue by christophlocher** [johannschopplich/kirby-blurry-placeholder#5]
First of all, thanks for the plugin – it’s awesome!

Unfortunately I am having some problems when using it for transparent PNG files, there are some heavy artifacts in the blurred version of the image: 

<img width="506" alt="image" src="https://user-images.githubusercontent.com/7572627/113491341-52e85b80-94d0-11eb-986e-545a5f0f0366.png">

**Comment by johannschopplich** [comment]
Hi Christoph,

first and foremost: thanks for the flowers.

That does look ugly, indeed. The plugin uses Kirby's thumbnail generation, which itself uses PHP's GD library (unless you're using ImageMagick). It seems like your transparent image isn't handled well. 
Maybe we can detect images containing transparent pixels and process them differently. Or seimpler, use a different SVG overlay for those images to hide the artifacts.

For the time being I don't have a quick solution, sorry. Would you mind posting the source image here so I can replicate the artifacts?

**Comment by christophlocher** [comment]
Sure! Here are the files from a different example.

This is the original:

![charapitachilli](https://user-images.githubusercontent.com/7572627/113588124-09af1d80-9630-11eb-8a2b-1a2611914093.png)

This is the thumbnail generated by Kirby (I took it from the media folder, scaled up for reference):

<img width="360" alt="image" src="https://user-images.githubusercontent.com/7572627/113588196-1cc1ed80-9630-11eb-8ca1-ec1004925be7.png">

And this is what it looks like in the fronend:

<img width="546" alt="image" src="https://user-images.githubusercontent.com/7572627/113588227-264b5580-9630-11eb-8d15-b6b2a4b0d2e0.png">

**Comment by medienbaecker** [comment]
I had a look at the way the blurry SVG is generated. In addition to the self-explanatory gaussian blur there's also a `feFuncA` which essentially eliminates the transparent areas on the blurry image. This makes sense for images without an alpha channel because you don't have to zoom but still receive a "full" image.

For transparent images it might make sense to simply remove this.

```diff
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {$svgWidth} {$svgHeight}">
  <filter id="b" color-interpolation-filters="sRGB">
    <feGaussianBlur stdDeviation=".5"></feGaussianBlur>
-   <feComponentTransfer>
-     <feFuncA type="discrete" tableValues="1 1"></feFuncA>
-   </feComponentTransfer>
  </filter>
  <image filter="url(#b)" x="0" y="0" width="100%" height="100%" href="{$placeholderImage}"></image>
</svg>
```

<img width="842" alt="CleanShot 2022-03-02 at 17 06 37@2x" src="https://user-images.githubusercontent.com/7975568/156400360-4cc0bef2-1421-4e78-9cf3-1a20174dc7e0.png">

**Comment by medienbaecker** [comment]
Depending on the project it might make sense to add a white background behind images via a feFlood filter instead:

```svg
<feFlood flood-color="white" result="bg" />
<feMerge>
  <feMergeNode in="bg"/>
  <feMergeNode in="SourceGraphic"/>
</feMerge>
```

**Comment by johannschopplich** [comment]
@medienbaecker Thanks a lot for your thorough research! Amazing. 🤯 
I haven't had the time to think of a better implementation yet. I prefer the latter solution.

**Comment by tobimori** [comment]
I use a forked version of this plugin in my project and added a custom transparent option that lets me toggle the snippet @medienbaecker highlighted. It's not the best idea, as I haven't implemented a way to detect transparent images, but most of the time when I use them I know beforehand (e.g. logos, clip arts, etc.), so I can set the value in code.

**Comment by johannschopplich** [comment]
@ChristophLabacher @medienbaecker With all of your help and @tobimori's implementation, this issue can finally be closed. Thank you all for your input! I wouldn't have managed to find time for a deep-dive into the issue. Feels good to finally close this.

With version [3.0.0](https://github.com/johannschopplich/kirby-blurry-placeholder/releases/tag/v3.0.0), the presence of an alpha channel in the image will be evaluated by the plugin. In any case, you can now pass an option parameter to disable the SVG filter, which resolves the blur artifacts:

```php
$file->placeholderUri([
  'transparent' => true
]);
```
