### ISSUE TITLE
Publish useLazyload as npm package

### ISSUE THREAD

**Issue by arnoson** [johannschopplich/kirby-blurry-placeholder#8]
I really like your updated version of lozad!

Right now, importing it from the plugin folder seems a bit verbose:

```js
import { useLazyload } from '../site/plugins/kirby-blurry-placeholder/src/useLazyload'
```

Would be great to just have an npm package. Or is there a shorter way to import it?

**Comment by johannschopplich** [comment]
You may set up an alias in your config, but that would be just another work-around. Probably a good idea to push the library to npm. Will keep that in mind.

**Comment by johannschopplich** [comment]
Hey @arnoson, it took me some time, but I have managed to finally rewrite the lazy loading hook in TypeScript: https://github.com/johannschopplich/loadeer (usage stays the some, it's a drop-in replacement).

I will keep the old hook in the project for compatibility reasons. But you can now just use the 🦌 `loadeer` npm package!

Head over to the [improved readme](https://github.com/johannschopplich/kirby-blurry-placeholder#lazy-loading-in-the-frontend) of the Kirby plugin to see a list of new features, like embedding the library without a build step.

I'm glad you like the library. 🙂

**Comment by arnoson** [comment]
Wow, looks like the perfect lazy loading library! Thank you very much (:
